version: '2'
services:
  swagger-consul:
    image: qnib/alpn-consul
    hostname: swagger-consul
    container_name: swagger-consul
    networks:
     - swagger
    ports:
     - "8500:8500"
    environment:
     - DC_NAME=swagger
     - CONSUL_BOOTSTRAP_EXPECT=1

  swagger-editor:
    image: qnib/swagger-editor
    hostname: swagger-editor
    container_name: swagger-editor
    networks:
     - swagger
    environment:
     - DC_NAME=swagger
     - CONSUL_CLUSTER_IPS=swagger-consul
    ports:
     - "8080:8080"
    # swagger-file
    volumes:
     - ./swagger-editor/spec-files/:/opt/swagger-editor/spec-files/
     - ./swagger-editor/config/:/opt/swagger-editor/config/

  source:
    build: source
    hostname: source
    container_name: source
    networks:
     - swagger
    environment:
     - DC_NAME=swagger
     - CONSUL_CLUSTER_IPS=swagger-consul
     - HTTP_PORT=8081
    ports:
     - "8081:8081"

  drain:
    build: drain
    hostname: drain
    container_name: drain
    networks:
     - swagger
    environment:
     - DC_NAME=swagger
     - CONSUL_CLUSTER_IPS=swagger-consul
     - HTTP_PORT=8082
    ports:
     - "8082:8082"

  microservice:
    build: microservice
    hostname: microservice
    container_name: microservice
    networks:
     - swagger
    environment:
     - DC_NAME=swagger
     - CONSUL_CLUSTER_IPS=swagger-consul
    ports:
     - "8083:8081"

networks:
    swagger:
