version: '2'
services:
  consul:
    extends:
      file: logs.yml
      service: consul
  elasticsearch:
    extends:
      file: logs.yml
      service: elasticsearch
    depends_on:
      - consul
  kopf:
    extends:
      file: logs.yml
      service: kopf
    depends_on:
      - consul
  kibana:
    extends:
      file: logs.yml
      service: kibana
    depends_on:
      - consul
  logstash:
    extends:
      file: logs.yml
      service: logstash
    depends_on:
      - consul

  bootnode:
    extends:
      file: ethereum.yml
      service: bootnode
    depends_on:
      - consul

  geth:
    extends:
      file: ethereum.yml
      service: geth
    ports:
      - 30303
    depends_on:
      - consul
    command: tail -f /dev/null

networks:
    ethereum-net:
    logs-net:
