# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "ubuntu",
    :ip => "192.168.100.11"
  }
]
$script = <<SCRIPT
    sleep 1
    rm -rf /var/lib/dpkg/lock
    apt-get update
    apt-get install -y apt-transport-https ca-certificates
    echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list
    apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    apt-get update
    apt-get install -y --allow-unauthenticated docker-engine
    cp /vagrant/docker.service /lib/systemd/system/
    systemctl daemon-reload
    systemctl restart docker
    echo ">> Going to pull the images"
    for x in ipfs geth webapp; do
        docker pull qnib/cp2017-${x}
    done
    echo ">> Going to start the stack on the virtualbox"
    #for x in ipfs geth webapp; do
    #    echo ">>>> docker run -d --name ${x} -net host qnib/cp2017-${x}"
    #    docker run -d --name ${x} --net host qnib/cp2017-${x}
    #done
    echo ">> Please do 'export DOCKER_HOST=192.168.100.10:2376' to connect to the docker daemon"
SCRIPT

# This defines the version of vagrant
Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = "janihur/ubuntu-1604-lxde-desktop"
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.ssh.forward_x11 = true
      node.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.customize ["modifyvm", :id, "--memory", 2048]
      end
      node.vm.provision "shell" do |s|
        s.inline = $script
      end
    end
  end
end
