# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
   echo "deb https://apt.dockerproject.org/repo ubuntu-xenial testing" > /etc/apt/sources.list.d/docker.list
   apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
   apt-get update
   apt-get install -y --allow-unauthenticated docker-engine 
   cp /vagrant/docker.service /lib/systemd/system/
   systemctl daemon-reload
   systemctl restart docker
   ip -o -4 addr
   echo ">> Chose one IP and do 'export DOCKER_HOST=192.168.0.11:2376'"
SCRIPT

# This defines the version of vagrant
Vagrant.configure(2) do |config|
  config.vm.define "host" do |node|
      node.vm.box = "bento/ubuntu-16.04"
      node.vm.hostname = "docker"
      node.vm.network "public_network"
      node.ssh.forward_x11 = true
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
      end
      node.vm.provision "shell" do |s|
        s.inline = $script
      end
  end
end
